spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        "[hibernate.enable_lazy_load_no_trans]": true
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[show_sql]": true
        "[format_sql]": true
logging:
  file:
    name: pergajuda.log
  level:
    root: info