spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: '@Serv3314'
    url: jdbc:sqlserver://localhost:1433;DatabaseName=bancoestudo
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        "[hibernate.enable_lazy_load_no_trans]": true
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        "[show_sql]": true
        "[format_sql]": true
logging:
  file:
    name: pergajuda.log
  level:
    root: info